name: Daily Data Update

on:
  schedule:
    - cron: '0 6 * * *'  # 6 AM UTC daily

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install packages
      run: |
        R -e 'install.packages(c("lubridate", "hoopR", "tidyverse", "janitor", "nanoparquet"))'
        
    - name: Run update script
      run: Rscript notebooks/2024_defender-and-shot-dashboards-import.R