name: Daily Data Update

on:
  schedule:
    - cron: '0 15 * * *'  # 7 AM PT daily
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
  
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::lubridate
          any::hoopR
          any::tidyverse
          any::janitor
          any::nanoparquet
          any::here
        
    - name: Run update script
      run: Rscript notebooks/2024_defender-and-shot-dashboards-import.R
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add data/*.parquet
        git commit -m "Update data files" || exit 0
        git push